logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: 192.168.0.3
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pizza-service
          uri: lb://pizza-service
          predicates:
            - Path=/api/1.0/pizzas/**
          filters:
            - RewritePath=/api/1.0/pizzas/(?<path>.*), /api/1.0/pizzas/$\{path}
        - id: pizzaorder-service
          uri: lb://pizzaorder-service
          predicates:
            - Path=/api/1.0/orders/**
        - id: pizza-auth-service
          uri: http://localhost:9100
          predicates:
            - Path=/auth/**
            - Method=POST
          filters:
            - RewritePath=/auth/(?<path>.*), /auth/$\{path}